MisPerris/MisPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url
#
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
from api import views

router =  routers.DefaultRouter()
router.register('user',views.UserViewSet)
router.register('groups',views.GroupViewSet)
# router.register('posts',views.PostViewSet)

urlpatterns = [
    path('mascotas/', include('mascotas.urls')),
    path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url('api/', include(router.urls)),
    path('', include('pwa.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += staticfiles_urlpatterns()

MisPerris/usuario/urls.py
from django.urls import path, re_path,include
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views 
from django.views.generic import TemplateView

app_name = 'usuario'
urlpatterns = [
    path('', include('pwa.urls')),
    url(r'^mantenedor/$', views.IndexView.as_view(), name='index'),
    path('registrar', views.index, name='lacasa'),
    path('login/', LoginView.as_view(template_name="usuario/login.html")),
    path('', views.home, name='home'),
    path('logout/', LogoutView.as_view(template_name="usuario/home.html")),
    path('adoptar', views.adoptar, name='adoptar'),
    url(r'^guardar_mascota/$', views.crud.guardarMascota, name='guardar_mascota'),
    url(r'^actualizar_mascota/$', views.crud.actualizarMascota, name='actualizar_mascota'),
    url(r'^actualizar_mascota/(?P<pk>\d+)/', views.adoptarMascota, name='adoptar_mascota'),
    url(r'^([0-9]+)/editar_mascota/$', views.crud.editarMascota, name='editar_mascota'),
    url(r'^([0-9]+)/eliminar_mascota/$', views.crud.eliminarMascota, name='eliminar_mascota'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name="usuario/password_reset.html")),
    url(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name="usuario/password_reset_done.html")),
    url(r'^password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name="usuario/password_reset_confirm.html")),
    url(r'serviceworker.js',  (TemplateView.as_view(template_name="serviceworker.js", content_type='application/javascript',)), name='serviceworker.js'),
]

MisPerris/usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ciudad = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

def create_profile(sender , **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

class Mascota(models.Model):
    nombre = models.CharField(max_length=200, blank='true')
    raza = models.CharField(max_length=15)
    Descripcion = models.CharField(max_length=200)
    Estado = models.CharField(max_length=200)
    image = models.ImageField(upload_to='mascota', blank='true')

    def __str__(self):
        return self.Descripcion
    def get_absolute_url(self): 
    	return self.image

class Choice(models.Model):
    question = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

MisPerris/usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
        labels = {
            'username':'Usuario',
            'first_name':'Nombres',
            'last_name':'Apellidos',
            'email':'Correo Electronico'
        }
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

#class adoptarForm(forms.ModelForm):        
#        class Meta:
#            model = UserProfile
#            fields = ('ciudad','region')
#            
#        def save(self, user=None):
#            user_profile = super(adoptarForm, self).save(commit=False)
#            user_profile.ciudad = self.cleaned_data['ciudad']
#            user_profile.region = self.cleaned_data['region']
#            if user:
#                user_profile.user = user
#            user_profile.save()
#            return user_profile

MisPerris/usuario/views.py
from django.shortcuts import render, redirect, reverse
from usuario.forms import RegistrationForm#, adoptarForm
from django.contrib.auth import logout
from django.http import JsonResponse
import json
from .models import UserProfile, Mascota
from django.contrib.auth.models import User

import os

from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect

from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core import serializers
from django.conf import settings

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('http://127.0.0.1:8000/usuario/home')
    else:
        form = RegistrationForm()
        context = {'form': form}
        return render(request, 'usuario/Formulario.html',context)
    
	
def adoptarMascota(request, pk):    
	Mascota.objects.filter(pk=pk).update(Estado='Adoptado')
	return HttpResponseRedirect(reverse('usuario:index')) 

def home(request):
	Mascotas = Mascota.objects.filter(Estado='Disponible')
	context = {'mascotas': Mascotas}
	return render(request, 'usuario/home.html', context)
	
def casa(request):
	template='usuario/home.html'
	return render(request,template)

def adoptar(request):    
        if request.method == 'POST':
                user = request.user
                us = UserProfile.objects.get(user=user)
                #form = adoptarForm(request.POST, instance=request.user)  
                us.region = request.POST["region"] 
                us.ciudad = request.POST["comunas"]
                print(request.user)
                us.save()
                        #form.save()
                        #return redirect('http://127.0.0.1:8000/usuario/home')
        #else:     
                #form = adoptarForm()
        return render(request, 'usuario/adoptar.html')#{'form': form})    
        
def serviceworker(request):
    response = render(request, app_settings.PWA_SERVICE_WORKER_PATH, content_type='application/javascript')
    return response


class crud():
	def guardarMascota(request):
		sv = Mascota(nombre=request.POST['nombre'], Descripcion=request.POST['descripcion'], image=request.FILES['image'],raza=request.POST['raza'],Estado=request.POST['estado'] )
		sv.save()
		return HttpResponseRedirect(reverse('usuario:index'))

	def editarMascota(request, data_id):
		data = get_object_or_404(Mascota, pk=data_id)
		alldata = Mascota.objects.order_by('-nombre') 
		return render(request, 'usuario/home2.html', {'data': data, 'qid' : data_id, 'getdata' : alldata})

	def actualizarMascota(request):
		ed = Mascota.objects.get(id=request.POST['qid'])
		
		imagePath = os.path.join(settings.MEDIA_ROOT, ed.image.name)

		if 'image' in request.FILES:
			ed.image = request.FILES['image']
			if os.path.isfile(imagePath):
				os.remove(imagePath)

	
		ed.nombre=request.POST['nombre']
		ed.raza=request.POST['raza']

		ed.Descripcion=request.POST['descripcion']
		
		ed.save()

		return HttpResponseRedirect(reverse('usuario:index'))

	def eliminarMascota(request, data_id):
		dl = Mascota.objects.get(id=data_id)

		imagePath = os.path.join(settings.MEDIA_ROOT, dl.image.name)
		

		if os.path.isfile(imagePath):
			os.remove(imagePath)

		

		dl.delete()

		return HttpResponseRedirect(reverse('usuario:index'))
        #def getimage(request):
                

class IndexView(generic.ListView):
	template_name = 'usuario/home2.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		return Mascota.objects.order_by('-nombre')
	

MisPerris/usuario/templates/usuario/Formulario.html
{% load static from staticfiles %}


<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Formulario de contacto</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'validarFormulario.js' %}"></script>
        
</head>
<body style="background:rgb(109,204,170); ">
      <div class="conteiner row formulario" style="width: 1000px;
      margin: 0 auto;">
        <form method="post" action="adoptar">
        {% csrf_token %}
        <ul>
            <h1>Formulario de Registro</h1>
          <li>
                {{ form.username.label }}
                <br>
                {{ form.username }}     
          </li>
          <li>
            {{ form.first_name.label }}
            <br>
            {{ form.first_name }}
          </li>
          <li>
            {{ form.last_name.label }}
            <br>
            {{ form.last_name }}
          </li>
          <li>
            <p>Correo Electronico <br>{{ form.email }}</p>
            
          </li>
          <li>
            <p>Contraseña <br> {{ form.password1 }}</p>
          </li>
          <li>
          <p>Confirmar Contraseña <br> {{ form.password2 }}</p>  
        </li>
        </ul>
      <button type="submit"> Register </button>
        </form>      
      </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="js/jquery.validate.js"></script>
	<script src="js/ValidarFormulario.js"></script>

</body>

</html>

MisPerris/usuario/templates/usuario/adoptar.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="{% static 'validarFormulario.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Adoptar
    </title>
</head>
<body>    
    <h2>¿De donde eres: {{ user.first_name }}?</h2>
    <form method ="post" action="adoptar">
        {% csrf_token %}
        <select id="regiones" name="region">
        </select>
        <select id="comunas" name="comunas">
        </select>
        <select id="tdv" name="tdv">
            <option value="dep">Departamento</option>
            <option value="casa">Casa</option>
            <option value="calle">La calle</option>
        </select>
        <button type="submit" value="Select">Adoptar</button>
    </form>
</body>
</html>

MisPerris/usuario/templates/usuario/home2.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">

{% load static %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" media="screen" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" media="screen" href="{% static 'css/dataTables.bootstrap.css' %}">
	<link rel="stylesheet" media="screen" href="{% static 'css/dataTables.tableTools.css' %}">
	<link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">

	<title>Mascotas</title>

	<!--  -->

	<style>

	</style>

</head>

<body>
   <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MASCOTAS </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://127.0.0.1:8000/usuario/home">Inicio</a></li>
            </ul>
        </div>
    </div>
    </nav>

	<div class="container">
<div class="row">
        {% if user != null %}
        <p>Bienvenido, estás conectado como: {{ user.first_name }} {{user.last_name }}</p>
        {% endif %}

    {% if user.username == "admin" %}
    <div class="col-md-4 col-sm-4 col-xs-4">
       <div class="panel panel-default">
            <div class="panel-heading">Formulario de mascotas</div>
            <div class="panel-body">
                {% if qid %}
                    <form method="POST" action="{% url 'usuario:actualizar_mascota' %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">Nombre</label>
                            <input required="required" class="form-control" placeholder="Nombre" name="nombre" type="text" value="{{ data.nombre }}">
                        </div>
                        <div class="form-group">
                            <label for="username">Raza</label>    
                            <input type="hidden" name="qid" value="{{ data.pk }}">
                            <input required="required" class="form-control" value="{{ data.raza }}" placeholder="Raza" name="raza" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Descripción</label>    
                            <input type="hidden" name="qid" value="{{ data.pk }}">
                            <input required="required" class="form-control" value="{{ data.Descripcion }}" placeholder="Descripción" name="descripcion" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Estado</label>    
                            <input type="hidden" name="qid" value="{{ data.pk }}">
                            <input required="required" class="form-control" value="{{ data.Estado }}" placeholder="Disponible-Adoptado-Rescatado" name="estado" type="text">                            
                        </div>
                        <div class="form-group">
                            <label for="username">Imagen</label>    
                            <input class="form-control" name="image" type="file">
                            <!--<img src="{{ MEDIA_URL }}{{ data.image }}" style="width: 200px;">-->
                            <img src="{{ data.image.url }}" style="width: 200px;">
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Actualizar Datos">
                        </div>
                    </form>
                {% else %}
                    <form method="POST" action="{% url 'usuario:guardar_mascota' %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">Nombre</label>
                            <input required="required" class="form-control" placeholder="Nombre" name="nombre" type="text" value="">
                        </div>
                        <div class="form-group">
                            <label for="username">Raza</label>    
                            <input required="required" class="form-control" value="" placeholder="Raza" name="raza" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Descripción</label>    
                            <input required="required" class="form-control" value="" placeholder="" name="descripcion" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Estado</label>    
                            <input required="required" class="form-control" value="" placeholder="Rescatado - Disponible - Adoptado" name="estado" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Imagen</label>    
                            <input required="required" class="form-control" name="image" type="file">
                        </div>
                        
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Guardar">
                        </div>
                    </form>
                {% endif %}

            </div>
        </div>
    </div>
    {% endif %}
    
    <div class="col-md-8 col-sm-8 col-xs-8">
        <div class="panel panel-default">
            <div class="panel-heading">Lista Mascota</div>
            <div class="panel-body">
                <table class="table table-striped table-bordered datatable" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nombre</th>
                            <th>Raza</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>Imagen</th>
                            <!--<th>Action</th>-->
                        </tr>
                    </thead>
                    <tbody>
                        {% if latest_question_list %}
                            {% for question in latest_question_list %}
                                <tr>
                                    <!-- instead $i++ in php -->
                                    <td>{{ forloop.counter }}</td> 
                                    <td>{{ question.nombre }}</td>
                                    <td>{{ question.raza }}</td>
                                    <td>{{ question.Descripcion }}</td>
                                    <td>{{ question.Estado }}</td>
                                    <!--<td><img src="{{ MEDIA_URL }}{{ question.image }}" style="width: 60px;"></td>-->
                                    <td><img src="{{ question.image.url }}" style="width: 60px;">
                                    <!--<td>{{ question.pub_date }}</td>-->
                                    <td>
                                        {% if user.username == "admin" %}
                                        <a href="{% url 'usuario:editar_mascota' question.id %}">Editar</a>
                                        <a onclick="return confirm('Esta seguro que quiere eliminar ?');" href="{% url 'usuario:eliminar_mascota' question.id %}">Eliminar</a>
                                        {% else %}
                                        <a href="{% url 'usuario:adoptar_mascota' question.id %}">Adoptar</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% elif getdata %}
                            {% for question in getdata %}
                                <tr>
                                    <td>{{ forloop.counter }}</td> 
                                    <td>{{ question.nombre }}</td>
                                    <td>{{ question.raza }}</td>
                                    <td>{{ question.Descripcion }}</td>
                                    <td>{{ question.Estado }}</td>
                                    <!--<td><img src="{{ MEDIA_URL }}{{ question.image }}" style="width: 60px;"></td>-->
                                    <td><img src="{{ question.image.url }}" style="width: 60px;">
                                    <!--<td>{{ question.pub_date }}</td>-->                                    
                                        
                                {% if user.username == "admin" %}
                                    <td>    
                                        <a href="{% url 'usuario:editar_mascota' question.id %}">Editar</a>                                        
                                        <a onclick="return confirm('Esta seguro que quiere eliminar ?');" href="{% url 'usuario:eliminar_mascota' question.id %}">Eliminar</a>
                                    </td>
                                    {% else %}
                                    <a href="">Adoptar</a>
                                {% endif %}
                                    
                                </tr>
                            {% endfor %}
                        {% else %}
                                <tr>
                                <td colspan="5">No hay data disponible ..</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
    
</div>
<footer class="footer">
    <div class="container">
        <p class="muted credit">MisPerris <a href="">Erick Morales</a></p>
    </div>
</footer>    
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>

</html>

MisPerris/usuario/templates/usuario/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'mascota/style.css' %}" />

{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li><a href="{% url 'usuario:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No Data are avaible.</p>
{% endif %}

MisPerris/usuario/templates/usuario/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
    <div class="container">
        <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Login </button>
        <button class="btn btn-primary" href="{ % provider_login_url "facebook" method="oauth2" %}">Ingresa con Facebook</button>
    </form>
    </div>
</body>
</html>

MisPerris/usuario/templates/usuario/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Reset Pass</title>
</head>
<body>
    <div class="container">
        <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Enviar </button>
    </form>
    </div>
</body>
</html>

MisPerris/usuario/templates/usuario/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Reset Pass</title>
</head>
<body>
    <div class="container">
        <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Enviar </button>
    </form>
    </div>
</body>
</html>

MisPerris/usuario/templates/usuario/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Reset Pass</title>
</head>
<body>
    <div class="container">
        <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Enviar </button>
    </form>
    </div>
</body>
</html>